# Cloudflare Worker 配置文件

name = "wxkf-own"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
name = "wechat-customer-service"
# 微信企业号配置
WECHAT_CORP_ID="1"
WECHAT_KF_SECRET="2"
WECHAT_KF_TOKEN="3"
WECHAT_KF_ENCODING_AES_KEY="4"

# 加密服务配置（由于 CF Worker CRYPTO 兼容性问题，需要单独部署）
CRYPTO_SERVICE_URL="https://rare-seahorse-61.deno.dev"

# OpenAI API 配置
OPENAI_API_KEY="sk-f3723273e483446eb9898b564e393c4f"
OPENAI_BASE_URL="https://api.deepseek.com/v1"
OPENAI_MODEL="DeepSeek-V3.2-Exp"
OPENAI_TIMEOUT=30000
# OPENAI_ORGANIZATION=org-your-org-id
# OPENAI_PROJECT=proj-your-project-id

# 系统提示词配置
SYSTEM_PROMPT="your are helpful assistant, reply in chinese, and reply in plain text format, text length should be less than 10240 characters" 


# KV存储配置（用于持久化对话历史）
[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "0c25366b4fc9460da840aa2a2cff2e35"
preview_id = ""

# KV存储配置（用于消息处理状态跟踪）
[[kv_namespaces]]
binding = "MESSAGE_TRACKER"
id = "6d173dd9fd1f4021bb1468db86c60127"
preview_id = ""